### PR TITLE
use latest version of p2pu-search-cards

### PR DESCRIPTION
**Pull request by s-kennedy**
This is dependent on https://github.com/p2pu/learning-circles/pull/368

### CODE REVIEW

**Comment by s-kennedy** [comment]
@dirkcuys aah I messed something up but I don't know what... bundler won't bundle ☹️there's nothing different in the Gemfile or Gemfile.lock so I'm not sure what's up, any ideas?

**Comment by dirkcuys** [comment]
@s-kennedy check the [last changes](https://github.com/p2pu/p2pu-website/commit/f7ad8486726c945b79f7365d2596a8dc60a7f6ec) I made on master. TravisCI had an issue with the bundler version being used, so I had to make a few updates.

Locally bundler worked fine, but I updated my ruby to 2.6, so not sure if there are issues with older versions?

**Comment by s-kennedy** [comment]
yay @dirkcuys tests are passing now! it was a stupid mistake on p2pu-search-cards. can you send me the command/script you mentioned for adding the additional fields to the course fixture?

**Comment by dirkcuys** [comment]
```
curl https://learningcircles.p2pu.org/api/learningcircles/\?distance\=50\&active\=true\&limit\=21\&signup\=open\ | json_pp > test/fixtures/learning-circles.json
```

**Comment by s-kennedy** [comment]
awesome thanks, although I realize now that the API changes for courses aren't on production yet so updating the course fixtures will have to wait until that's live.

**Pull request merged**
