### PR TITLE
bump p2pu-components version to use lc card with meeting frequency

### PR DESCRIPTION
**Pull request by s-kennedy**
**Deploying site to**: [p2pu-website-better-marmot.s3-website-us-east-1.amazonaws.com
](http://p2pu-website-better-marmot.s3-website-us-east-1.amazonaws.com
)

### CODE REVIEW

**Comment by s-kennedy** [comment]
Relevant commit https://github.com/p2pu/p2pu-components/commit/48832cfdbbd3c6da17ede6400e56dc29a37d2192

Goes with https://github.com/p2pu/learning-circles/pull/743 but it's not dependent on it

**Comment by s-kennedy** [comment]
Updated text: https://github.com/p2pu/p2pu-components/commit/860cb56d8d431674f4297056bcf1ff1549f23ed2

**Comment by dirkcuys** [comment]
@beckymargraf @GrifP could either of you please have a look through the staging site mentioned at the top and check that things make sense.

**Comment by beckymargraf** [comment]
@dirkcuys I found two copy issues:

image
^ For upcoming learning circles with closed sign-ups, the date should read "Starting [date]":

image
^ LCs with 1 meeting shouldn't pluralize "meetings"

**Comment by GrifP** [comment]
@dirkcuys - does this incorporate the changed copy on the learning circle sign up pages itself? (There was a similar change to the way the terms "meetings" and "weeks" are used on the top of the sign up pages, but I don't see it reflected in this issue.

**Pull request merged**
